pique improvements for testing 74

diff --git a/scripts/dump_db b/scripts/dump_db
--- a/scripts/dump_db
+++ b/scripts/dump_db
@@ -1,10 +1,23 @@
 #!/bin/bash
-set -e
-
 mysql -uroot -proot -e "drop database if exists $1; create database $1;"
 
 wget -O /tmp/$1.sql.gz http://172.16.77.252/backup/MySQL/Opac3/Daily/`date +%d-%m-%Y`/$1_`date +%Y%m%d`_OPAC3_MyISAM_backup.sql.gz
-# wget -O /tmp/$1.sql.gz http://172.16.77.252/backup/MySQL/Opac3/Daily/03-07-2015/$1_20150703_OPAC3_MyISAM_backup.sql.gz
-zcat /tmp/$1.sql.gz |mysql -uroot -proot $1 
-echo "dump completed"
+
+if [[ `echo "$?"` == 0 ]]; then 
+    zcat /tmp/$1.sql.gz |mysql -uroot -proot $1 
+    echo "dump from today completed"
+    exit 0
+fi
+
+
+wget -O /tmp/$1.sql.gz http://172.16.77.252/backup/MySQL/Opac3/Daily/`date --date="yesterday" +%d-%m-%Y`/$1_`date --date="yesterday" +%Y%m%d`_OPAC3_MyISAM_backup.sql.gz
+
+if [[ `echo "$?"` == 0 ]]; then 
+    zcat /tmp/$1.sql.gz |mysql -uroot -proot $1 
+    echo "dump from yesterday completed"
+    exit 0
+fi
+
+echo "Could not dump"
+exit 1
 
